version: 2
project_name: sqvue

builds:
  - id: sqvue
    main: .
    binary: sqvue
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X sqvue/cmd.version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: sqvue
    ids:
      - sqvue
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  prerelease: auto
  extra_files:
    - glob: ./scripts/install.sh

changelog:
  use: git
