package tui

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/bubbles/key"
	tea "github.com/charmbracelet/bubbletea"

	"sqvue/internal/db"
)

type rowInsertFieldMode uint8

const (
	rowInsertUseDefault rowInsertFieldMode = iota
	rowInsertLiteral
	rowInsertNull
	rowInsertCurrentTimestamp
)

type rowInsertField struct {
	column db.Column
	mode   rowInsertFieldMode
	value  string
}

func (m Model) canInsertRow() bool {
	if !m.focused || m.queryActive || m.mode != modeValues {
		return false
	}
	table := m.currentTable()
	if table == nil || table.Type != "table" || len(m.columns) == 0 {
		return false
	}
	_, ok := m.client.(db.RowInserter)
	return ok
}

func (m Model) beginRowInsert() (Model, tea.Cmd) {
	if m.queryActive {
		m.status = "inserting is unavailable for SQL results"
		return m, nil
	}
	table := m.currentTable()
	if table == nil || table.Type != "table" {
		m.status = "inserting is available only for tables"
		return m, nil
	}
	if _, ok := m.client.(db.RowInserter); !ok {
		m.status = "inserting is unavailable for this connection"
		return m, nil
	}
	m.rowInsertFields = make([]rowInsertField, len(m.columns))
	for i, column := range m.columns {
		m.rowInsertFields[i] = rowInsertField{column: column}
	}
	m.rowInsertCursor, m.rowInsertScroll = 0, 0
	m.activeOverlay = overlayRowInsert
	m.status = "new row"
	return m, nil
}

func (m Model) handleRowInsertKey(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch {
	case msg.String() == "esc":
		m.closeRowInsertForm()
		m.restoreBrowseStatus()
	case key.Matches(msg, m.keys.Quit):
		return m, tea.Quit
	case key.Matches(msg, m.keys.Down):
		m.rowInsertCursor = min(m.rowInsertCursor+1, len(m.rowInsertFields)-1)
	case key.Matches(msg, m.keys.Up):
		m.rowInsertCursor = max(0, m.rowInsertCursor-1)
	case key.Matches(msg, m.keys.Confirm) || msg.String() == "e":
		return m.beginRowInsertValue()
	case msg.String() == "d":
		return m.setRowInsertFieldMode(rowInsertUseDefault)
	case msg.String() == "n":
		return m.setRowInsertFieldMode(rowInsertNull)
	case msg.String() == "t":
		return m.setRowInsertFieldMode(rowInsertCurrentTimestamp)
	case key.Matches(msg, m.keys.RunSQL):
		_, err := m.rowInsertRequest()
		if err != nil {
			return m.fail("row insert is incomplete", err)
		}
		m.rowInsertInput.Blur()
		m.activeOverlay = overlayRowInsertConfirm
		m.status = "confirm row insert"
	}
	m.rowInsertScroll = keepInView(m.rowInsertCursor, m.rowInsertScroll, m.rowInsertFormHeight(), len(m.rowInsertFields))
	return m, nil
}

func (m Model) beginRowInsertValue() (Model, tea.Cmd) {
	field, ok := m.activeRowInsertField()
	if !ok {
		return m, nil
	}
	if field.column.IsGenerated {
		m.status = sanitizeText(field.column.Name) + " is generated by the database"
		return m, nil
	}
	m.rowInsertEditPrevious = field
	m.rowInsertInput.Prompt = "Value " + sanitizeText(field.column.Name) + ": "
	m.rowInsertInput.SetValue(field.value)
	m.rowInsertInput.Focus()
	m.activeOverlay = overlayRowInsertValue
	m.status = "enter a literal value"
	return m, nil
}

func (m Model) handleRowInsertValueKey(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch {
	case msg.String() == "esc":
		m.restoreRowInsertEditPrevious()
		m.rowInsertInput.Blur()
		m.activeOverlay = overlayRowInsert
		m.status = "new row"
	case key.Matches(msg, m.keys.Confirm):
		if field, ok := m.activeRowInsertField(); ok {
			field.mode, field.value = rowInsertLiteral, m.rowInsertInput.Value()
			m.rowInsertFields[m.rowInsertCursor] = field
		}
		m.rowInsertInput.Blur()
		m.activeOverlay = overlayRowInsert
		m.status = "new row"
	default:
		var cmd tea.Cmd
		m.rowInsertInput, cmd = m.rowInsertInput.Update(msg)
		m.rowInsertInput.SetValue(sanitizeText(m.rowInsertInput.Value()))
		return m, cmd
	}
	return m, nil
}

func (m Model) setRowInsertFieldMode(mode rowInsertFieldMode) (Model, tea.Cmd) {
	field, ok := m.activeRowInsertField()
	if !ok {
		return m, nil
	}
	if field.column.IsGenerated {
		m.status = sanitizeText(field.column.Name) + " is generated by the database"
		return m, nil
	}
	if mode == rowInsertCurrentTimestamp && !isDateTimeColumn(field.column.DataType) {
		m.status = sanitizeText(field.column.Name) + " is not a date/time column"
		return m, nil
	}
	field.mode, field.value = mode, ""
	m.rowInsertFields[m.rowInsertCursor] = field
	m.status = "new row"
	return m, nil
}

func (m Model) rowInsertRequest() (db.RowInsertRequest, error) {
	table := m.currentTable()
	if table == nil {
		return db.RowInsertRequest{}, fmt.Errorf("no table is selected")
	}
	request := db.RowInsertRequest{Table: *table}
	for _, field := range m.rowInsertFields {
		if field.column.IsGenerated {
			continue
		}
		if field.mode == rowInsertUseDefault {
			if rowInsertFieldRequired(field) {
				return db.RowInsertRequest{}, fmt.Errorf("%s requires a value", sanitizeText(field.column.Name))
			}
			continue
		}
		value := db.RowInsertValue{Column: field.column.Name}
		switch field.mode {
		case rowInsertLiteral:
			value.Kind, value.Value = db.RowInsertLiteral, field.value
		case rowInsertNull:
			value.Kind = db.RowInsertNull
		case rowInsertCurrentTimestamp:
			value.Kind = db.RowInsertCurrentTimestamp
		default:
			return db.RowInsertRequest{}, fmt.Errorf("%s has an invalid value", sanitizeText(field.column.Name))
		}
		request.Values = append(request.Values, value)
	}
	if err := request.Validate(); err != nil {
		return db.RowInsertRequest{}, err
	}
	return request, nil
}

func rowInsertFieldRequired(field rowInsertField) bool {
	return !field.column.Nullable && field.column.Default == nil && !field.column.IsAutoGenerated && !field.column.IsGenerated
}

func isDateTimeColumn(dataType string) bool {
	dataType = strings.ToLower(dataType)
	return strings.Contains(dataType, "date") || strings.Contains(dataType, "time")
}

func (m Model) handleRowInsertConfirmKey(msg tea.KeyMsg) (Model, tea.Cmd) {
	switch {
	case msg.String() == "esc":
		m.activeOverlay = overlayRowInsert
		m.status = "new row"
	case key.Matches(msg, m.keys.Confirm):
		inserter, ok := m.client.(db.RowInserter)
		if !ok {
			m.activeOverlay = overlayNone
			m.status = "inserting is unavailable for this connection"
			return m, nil
		}
		request, err := m.rowInsertRequest()
		if err != nil {
			m.activeOverlay = overlayRowInsert
			return m.fail("row insert is incomplete", err)
		}
		m.activeOverlay = overlayNone
		m.closeTableStream()
		m.insertID++
		m.loading = true
		m.status = "inserting row..."
		return m, insertRowCmd(inserter, request, m.timeout, m.insertID)
	}
	return m, nil
}

func (m Model) activeRowInsertField() (rowInsertField, bool) {
	if m.rowInsertCursor < 0 || m.rowInsertCursor >= len(m.rowInsertFields) {
		return rowInsertField{}, false
	}
	return m.rowInsertFields[m.rowInsertCursor], true
}

func (m *Model) restoreRowInsertEditPrevious() {
	if m.rowInsertCursor >= 0 && m.rowInsertCursor < len(m.rowInsertFields) {
		m.rowInsertFields[m.rowInsertCursor] = m.rowInsertEditPrevious
	}
}

func (m *Model) closeRowInsertForm() {
	m.rowInsertFields = nil
	m.rowInsertCursor, m.rowInsertScroll = 0, 0
	m.rowInsertInput.Blur()
	m.activeOverlay = overlayNone
}

func (m *Model) clearCurrentRowCounts() {
	table := m.currentTable()
	if table == nil {
		return
	}
	delete(m.rowCounts, table.String())
	for key := range m.browseRowCounts {
		if key == table.String() || strings.HasPrefix(key, table.String()+"\x00") {
			delete(m.browseRowCounts, key)
		}
	}
}

func (m Model) rowInsertFormHeight() int {
	if m.height <= 0 {
		return tableListHeight
	}
	return max(1, m.height-12)
}

func (m Model) rowInsertSuccessStatus() string {
	if len(m.browseFilters) > 0 {
		return "inserted row; active filters may hide it"
	}
	return "inserted row"
}
