package db

import (
	"context"
	"fmt"
	"strings"
)

// BackupScope identifies the database object captured by a backup.
type BackupScope string

const (
	BackupScopeDatabase BackupScope = "database"
	BackupScopeSchema   BackupScope = "schema"
	BackupScopeTable    BackupScope = "table"
)

// BackupRequest describes a driver-managed database backup. Path is the final
// artifact path and must not name an existing file. Drivers are responsible for
// preserving their database-specific schema and data objects.
type BackupRequest struct {
	Scope  BackupScope
	Path   string
	Schema string
	Table  Table
}

// Validate checks that a request contains the target required by its scope.
// It intentionally does not validate driver-specific backup options.
func (r BackupRequest) Validate() error {
	if strings.TrimSpace(r.Path) == "" {
		return fmt.Errorf("backup path is required")
	}
	switch r.Scope {
	case BackupScopeDatabase:
		return nil
	case BackupScopeSchema:
		if strings.TrimSpace(r.Schema) == "" {
			return fmt.Errorf("schema backup requires a schema")
		}
		return nil
	case BackupScopeTable:
		if strings.TrimSpace(r.Table.Schema) == "" || strings.TrimSpace(r.Table.Name) == "" {
			return fmt.Errorf("table backup requires a schema and table")
		}
		return nil
	default:
		return fmt.Errorf("unsupported backup scope %q", r.Scope)
	}
}

// BackupCapabilities identifies the scopes and output type supported by a
// driver. FileExtension is the extension (without a leading dot) for backup
// files generated by the driver.
type BackupCapabilities struct {
	Database      bool
	Schema        bool
	Table         bool
	FileExtension string
}

// BackupDriver is an optional Driver capability. Implementations own command
// invocation, quoting, connection handling, and database-specific backup
// semantics; the shared db package only defines the neutral request contract.
type BackupDriver interface {
	Driver
	BackupCapabilities() BackupCapabilities
	Backup(context.Context, BackupRequest) error
}
